TECH_FRESHNESS_PACKS = {
    "react": {
        "name": "React",
        "keywords": ["react", "reactjs", "react.js"],
        "modern_patterns": {
            "hooks": [
                "usestate",
                "useeffect",
                "usecallback",
                "usememo",
                "usecontext",
                "usereducer",
                "custom hook",
                "react hooks",
            ],
            "modern_api": [
                "react 18",
                "react 19",
                "concurrent mode",
                "suspense",
                "lazy()",
                "react.lazy",
                "starttransition",
                "usedeferredvalue",
                "usesyncexternalstore",
                "server component",
                "rsc",
                "next.js",
                "nextjs",
                "next 14",
                "next 15",
            ],
            "modern_tooling": [
                "vite",
                "vitest",
                "react testing library",
                "rtl",
                "playwright",
                "pnpm",
            ],
            "modern_patterns": [
                "functional component",
                "function component",
                "arrow function component",
                "jsx",
                "tsx",
                "react.fc",
                "prop drilling",
                "composition pattern",
            ],
        },
        "outdated_patterns": {
            "class_components": [
                "class component",
                "react.component",
                "extends component",
                "this.state",
                "this.setstate",
                "constructor(props)",
                "componentdidmount",
                "componentwillunmount",
                "componentwillmount",
                "componentwillreceiveprops",
                "componentwillupdate",
                "shouldcomponentupdate",
                "this.props",
            ],
            "legacy_tooling": [
                "create-react-app",
                "cra",
                "webpack config",
                "babel config",
                "eject",
            ],
            "legacy_routing": [
                "react router v5",
                "react router v4",
                "withrouter",
                "switch>",
                "switch>",
            ],
            "deprecated_apis": [
                "react.finddomnode",
                "string refs",
                "this.refs",
                "react.createref",
                "defaultprops",
                "react.memo on class",
            ],
        },
        "version_rules": {
            "current_major": 19,
            "current_minor_range": (18, 19),
            "still_acceptable": [16, 17],
            "outdated": [15, 14, 13],
        },
    },
    "node": {
        "name": "Node.js",
        "keywords": ["node", "nodejs", "node.js", "express", "nestjs", "fastify"],
        "modern_patterns": {
            "modern_runtime": [
                "node 20",
                "node 22",
                "node 21",
                "node 23",
                "lts",
                "esm",
                "ecmascript module",
                "import from",
                "type: module",
                "node --import",
            ],
            "modern_api": [
                "fetch()",
                "node fetch",
                "async/await",
                "promises",
                "stream/promises",
                "fs/promises",
                "node:test",
                "built-in test runner",
                "watch mode",
                "node --watch",
            ],
            "modern_tooling": [
                "tsx",
                "tsup",
                "esbuild",
                "vite",
                "pnpm",
                "biome",
                "eslint flat config",
                "prettier",
            ],
            "modern_patterns": [
                "middleware",
                "error handler",
                "graceful shutdown",
                "health check",
                "structured logging",
                "pino",
            ],
        },
        "outdated_patterns": {
            "legacy_runtime": ["node 14", "node 16", "node 12", "node 10"],
            "legacy_api": [
                "require(",
                "module.exports",
                "callback hell",
                "__dirname",
                "__filename without",
                "fs.readfilesync",
                "fs.writefilesync",
                "request library",
                "axios in node",
            ],
            "legacy_tooling": [
                "nodemon",
                "babel-node",
                "commonjs",
                "ts-node",
                "webpack dev server",
            ],
            "deprecated_apis": [
                "node-sass",
                "npminstall",
                "body-parser",
                "express.urlencoded",
                "morgan",
                "shelljs",
            ],
        },
        "version_rules": {
            "current_major": 22,
            "current_minor_range": (20, 22),
            "still_acceptable": [18],
            "outdated": [16, 14, 12],
        },
    },
    "python": {
        "name": "Python",
        "keywords": [
            "python",
            "python3",
            "django",
            "flask",
            "fastapi",
            "pytorch",
            "pandas",
        ],
        "modern_patterns": {
            "modern_syntax": [
                "f-string",
                'f"',
                'f"',
                "walrus operator",
                ":=",
                "match case",
                "pattern matching",
                "type hints",
                "typing",
                "def -> ",
                ": dict[",
                ": list[",
                "from __future__",
            ],
            "modern_api": [
                "asyncio",
                "async def",
                "await ",
                "pathlib",
                "dataclass",
                "@dataclass",
                "pydantic",
                "httpx",
                "aiohttp",
            ],
            "modern_tooling": [
                "uv",
                "rye",
                "poetry",
                "ruff",
                "black",
                "mypy",
                "pytest",
                "hatch",
            ],
            "modern_patterns": [
                "context manager",
                "with statement",
                "generator",
                "yield",
                "list comprehension",
                "dict comprehension",
                "protocol",
                "abc",
            ],
        },
        "outdated_patterns": {
            "legacy_python": [
                "python 2",
                "python2",
                "print ",
                "xrange",
                "raw_input",
                "unicode(",
                "basestring",
                "except ,",
            ],
            "legacy_api": [
                "urllib2",
                "urlparse",
                "ConfigParser",
                "raw_input",
                "dict.iteritems",
                "dict.itervalues",
                "dict.iterkeys",
            ],
            "legacy_tooling": [
                "setup.py install",
                "pip install -e . from setup",
                "virtualenv",
                "pyenv global 2",
                "pipenv",
                "nose",
                "unittest2",
            ],
            "deprecated_apis": [
                "django 1.",
                "flask 0.",
                "request.get (sync)",
                "os.path instead of pathlib",
                "glob.glob instead of Path.glob",
            ],
        },
        "version_rules": {
            "current_major": 3,
            "current_minor_range": (12, 13),
            "still_acceptable": [10, 11],
            "outdated": [8, 9],
        },
    },
    "java": {
        "name": "Java",
        "keywords": [
            "java",
            "spring",
            "spring boot",
            "gradle",
            "maven",
            "jvm",
            "kotlin",
        ],
        "modern_patterns": {
            "modern_syntax": [
                "record",
                "sealed class",
                "pattern matching",
                "switch expression",
                "text block",
                "var ",
                "instanceof pattern",
                "virtual threads",
                "structured concurrency",
            ],
            "modern_api": [
                "stream api",
                "optional",
                "completablefuture",
                "httpclient",
                "java.nio",
                "java.time",
                "spring boot 3",
                "spring 6",
                "spring webflux",
            ],
            "modern_tooling": [
                "gradle",
                "junit 5",
                "mockito",
                "spring boot starter",
                "docker",
                "kubernetes",
                "micrometer",
                "actuator",
            ],
            "modern_patterns": [
                "dependency injection",
                "dependency inversion",
                "microservice",
                "reactive programming",
                "builder pattern",
                "functional interface",
            ],
        },
        "outdated_patterns": {
            "legacy_syntax": [
                "java 8",
                "java 11",
                "java.util.date",
                "simpledateformat",
                "vector",
                "hashtable",
                "stringbuffer",
                "java 7",
                "java 6",
            ],
            "legacy_api": [
                "java.io.file",
                "httpurlconnection",
                "javax.",
                "jsp",
                "servlet",
                "ejb",
                "spring xml config",
                "xml bean",
            ],
            "legacy_tooling": [
                "ant",
                "junit 3",
                "junit 4",
                "log4j 1",
                "svn",
                "websphere",
                "jboss",
            ],
            "deprecated_apis": [
                "spring boot 1",
                "spring boot 2",
                "apache commons lang 2",
                "guava old version",
            ],
        },
        "version_rules": {
            "current_major": 21,
            "current_minor_range": (17, 21),
            "still_acceptable": [11],
            "outdated": [8, 7],
        },
    },
    "javascript_typescript": {
        "name": "JavaScript/TypeScript",
        "keywords": [
            "javascript",
            "typescript",
            "js",
            "ts",
            "es6",
            "es2020",
            "esnext",
            "deno",
            "bun",
            "npm",
        ],
        "modern_patterns": {
            "modern_syntax": [
                "const ",
                "let ",
                "arrow function",
                "=>",
                "destructuring",
                "spread operator",
                "optional chaining",
                "?.",
                "nullish coalescing",
                "??",
                "template literal",
                "import/export",
                "async/await",
                "promise",
            ],
            "modern_api": [
                "fetch",
                "structuredClone",
                "AbortController",
                "IntersectionObserver",
                "ResizeObserver",
                "web workers",
                "service worker",
                "indexeddb",
                "crypto.subtle",
            ],
            "modern_tooling": [
                "typescript",
                "tsx",
                "esbuild",
                "swc",
                "vitest",
                "playwright",
                "pnpm",
                "bun",
                "deno",
                "biome",
            ],
            "modern_patterns": [
                "es module",
                "dynamic import",
                "module federation",
                "lazy loading",
                "code splitting",
                "tree shaking",
                "ssr",
                "ssg",
            ],
        },
        "outdated_patterns": {
            "legacy_syntax": [
                "var ",
                "function expression",
                "prototype",
                "object.create",
                "arguments[",
                "callback hell",
                "pyramid of doom",
                "jquery",
                "underscore.js",
                "moment.js",
            ],
            "legacy_api": [
                "xmlhttprequest",
                "xdomainrequest",
                "activexobject",
                "document.write",
                "eval(",
                "with (",
                "window.alert(",
                "confirm(",
                "prompt(",
            ],
            "legacy_tooling": [
                "grunt",
                "gulp",
                "bower",
                "browserify",
                "babel transpile",
                "webpack 4",
                "karma",
                "phantomjs",
                "ie11",
                "internet explorer",
            ],
            "deprecated_apis": [
                "moment.js",
                "lodash",
                "axios interceptor abuse",
                "redux saga",
                "mobx 5",
                "enzyme",
                "react test utils",
            ],
        },
        "version_rules": {
            "current_major": 2025,
            "current_minor_range": (2024, 2025),
            "still_acceptable": [2022, 2023],
            "outdated": [2020, 2019],
        },
    },
    "devops": {
        "name": "DevOps",
        "keywords": [
            "devops",
            "docker",
            "kubernetes",
            "k8s",
            "ci/cd",
            "jenkins",
            "github actions",
            "terraform",
            "ansible",
            "aws",
            "azure",
            "gcp",
            "helm",
        ],
        "modern_patterns": {
            "modern_tools": [
                "docker",
                "kubernetes",
                "k8s",
                "helm",
                "terraform",
                "github actions",
                "gitlab ci",
                "argocd",
                "prometheus",
                "grafana",
                "istio",
                "envoy",
                "vault",
            ],
            "modern_practices": [
                "gitops",
                "infrastructure as code",
                "iac",
                "immutable infrastructure",
                "blue-green",
                "canary deployment",
                "service mesh",
                "zero trust",
                "shift left",
                "supply chain security",
            ],
            "modern_api": [
                "kubernetes api",
                "docker api",
                "terraform cloud",
                "opentofu",
                "crossplane",
                "flux",
            ],
            "modern_tooling": [
                "pulumi",
                "crossplane",
                "flux",
                "argocd",
                "skaffold",
                "tilt",
                "devspace",
                "k9s",
                "kustomize",
            ],
        },
        "outdated_patterns": {
            "legacy_tools": [
                "jenkins pipeline",
                "puppet",
                "chef",
                "saltstack",
                "ansible playbook (old)",
                "vagrant",
                "virtualbox",
                "vmware",
                "nagios",
                "zabbix (old)",
            ],
            "legacy_practices": [
                "snowflake server",
                "manual deployment",
                "ssh into production",
                "ftp deploy",
                "manual scaling",
                "pets vs cattle (old mindset)",
                "monolith on bare metal",
            ],
            "deprecated_apis": [
                "docker compose v1",
                "docker-machine",
                "kubernetes v1.21",
                "helm v2",
                "terraform 0.11",
                "jenkins scripted pipeline",
            ],
        },
        "version_rules": {
            "current_major": 2025,
            "current_minor_range": (2024, 2025),
            "still_acceptable": [2022, 2023],
            "outdated": [2020, 2019],
        },
    },
}

EVERGREEN_TOPICS = {
    "keywords": [
        "algorithm",
        "data structure",
        "sorting",
        "binary search",
        "dynamic programming",
        "networking fundamentals",
        "tcp",
        "udp",
        "dns",
        "http fundamentals",
        "os basics",
        "operating system",
        "computer science",
        "discrete math",
        "big o notation",
        "git basics",
        "git fundamentals",
        "version control basics",
        "design patterns fundamentals",
        "solid principles",
        "clean code",
        "binary tree",
        "linked list",
        "hash table",
        "graph theory",
        "finite state machine",
        "recursion",
        "complexity analysis",
    ],
    "title_patterns": [
        "how the internet works",
        "how dns works",
        "how tcp works",
        "what is ip",
        "introduction to algorithms",
        "learn git",
        "computer science fundamentals",
        "how computers work",
        "networking basics",
        "os fundamentals",
    ],
}

OUTDATED_COMMENT_SIGNALS = {
    "explicit_outdated": [
        "doesn't work anymore",
        "not working",
        "outdated",
        "deprecated",
        "old method",
        "no longer works",
        "this is obsolete",
        "still relevant in",
        "as of 2024",
        "as of 2025",
        "as of 2026",
        "update:",
        "in the new version",
        "new api replaced",
        "different now",
        "changed in",
        "broken after update",
    ],
    "helpful_correction": [
        "actually you should",
        "the correct way is",
        "easier way to do this",
        "for anyone watching in",
        "better approach is",
        "update for new version",
        "modern way is",
        "current best practice",
        "this has been replaced",
    ],
    "still_relevant": [
        "still works",
        "still relevant",
        "works in latest",
        "works perfectly",
        "timeless content",
        " fundamentals",
        "good explanation even in",
    ],
    "spam_low_quality": [
        "subscribe",
        "check my channel",
        "guys check out",
        "free course",
        "discount code",
        "promo code",
        "click my link",
        "whatsapp me",
        "telegram me",
    ],
}

SCORING_WEIGHTS = {
    "modern_pattern_hit": 0.6,
    "outdated_pattern_hit": -0.9,
    "explicit_outdated_comment": -1.5,
    "helpful_correction_comment": -0.3,
    "still_relevant_comment": 0.8,
    "evergreen_bonus": 1.5,
    "base_score": 5.0,
    "minimum_score": 1.0,
    "maximum_score": 10.0,
}
